from enum import Enum


class InputType(str, Enum):
    FILE = "FILE"
    TEXT = "TEXT"


class DocumentType(str, Enum):
    PRESCRIPTION = "PRESCRIPTION"
    IMAGING_REPORT = "IMAGING_REPORT"
    STUDY_REPORT = "STUDY_REPORT"
    PROCEDURE_ORDER = "PROCEDURE_ORDER"
    DISCHARGE_SUMMARY = "DISCHARGE_SUMMARY"
    MEDICAL_CERTIFICATE = "MEDICAL_CERTIFICATE"


class Priority(str, Enum):
    ROUTINE = "ROUTINE"
    URGENT = "URGENT"


class RoutingDestination(str, Enum):
    MEDICAL_EMERGENCY = "MEDICAL_EMERGENCY"
    PHARMACY = "PHARMACY"
    AUTHORIZATION_AUDIT = "AUTHORIZATION_AUDIT"
    MEDICAL_RECORD = "MEDICAL_RECORD"
    HUMAN_REVIEW = "HUMAN_REVIEW"


class SemanticAuditReason(str, Enum):
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    ILLEGIBLE_DOCUMENT = "ILLEGIBLE_DOCUMENT"
    MISSING_CRITICAL_FIELDS = "MISSING_CRITICAL_FIELDS"
    INCONSISTENT_DATA = "INCONSISTENT_DATA"