from enum import Enum


class InputType(str, Enum):
    FILE = "FILE"
    TEXT = "TEXT"


class DocumentType(str, Enum):
    RECETA = "RECETA"
    INFORME_IMAGENES = "INFORME_IMAGENES"
    INFORME_ESTUDIO = "INFORME_ESTUDIO"
    ORDEN_PROCEDIMIENTO = "ORDEN_PROCEDIMIENTO"
    EPICRISIS = "EPICRISIS"
    CERTIFICADO_MEDICO = "CERTIFICADO_MEDICO"


class PriorityLevel(str, Enum):
    RUTINA = "RUTINA"
    URGENTE = "URGENTE"


class RoutingDestination(str, Enum):
    EMERGENCIA_MEDICA = "EMERGENCIA_MEDICA"
    FARMACIA = "FARMACIA"
    AUDITORIA_AUTORIZACIONES = "AUDITORIA_AUTORIZACIONES"
    HISTORIA_CLINICA = "HISTORIA_CLINICA"
    REVISION_HUMANA = "REVISION_HUMANA"


class SemanticAuditReason(str, Enum):
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    ILLEGIBLE_DOCUMENT = "ILLEGIBLE_DOCUMENT"
    MISSING_CRITICAL_FIELDS = "MISSING_CRITICAL_FIELDS"
    INCONSISTENT_DATA = "INCONSISTENT_DATA"