package com.mediflow.backend.enums;

public enum AuditReason {
    LOW_CONFIDENCE, ILLEGIBLE_DOCUMENT, MISSING_CRITICAL_FIELDS, INCONSISTENT_DATA,
    AI_TIMEOUT, AI_UNAVAILABLE, INVALID_AI_RESPONSE
}